# Common environment for services
x-common-env: &common-env
  tty: true
  stdin_open: true
  stop_grace_period: 1s

# Services
# for RPi, we only need the last package
services:
  # realsense: 
  #   build:
  #     context: .
  #     target: realsense  
  #     args:
  #       USER: realsense
  #       LIBREALSENSE_VERSION: 2.56.2
  #   <<: *common-env
  #   network_mode: host
  #   image: vision-tdk:realsense
  #   container_name: tdk-realsense
  #   volumes:
  #     - /dev:/dev
  #     - $PWD/../packages/realsense-pkg:/home/realsense/vision-ws/src/realsense-ros
  #   environment:
  #     - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
  #     - ROS_DOMAIN_ID=42
  #   device_cgroup_rules:
  #     - "c 81:* rmw"
  #     - "c 189:* rmw"
  #   command: bash
  #   #bash -ic "colcon build && ros2 launch realsense2_camera rs_launch.py"

  # gui:
  #   build:
  #     context: .
  #     target: gui
  #     args:
  #       USER: gui
  #   <<: *common-env
  #   network_mode: host
  #   image: vision-tdk:gui
  #   container_name: tdk-gui
  #   volumes:
  #     # X11 socket
  #     - /tmp/.X11-unix:/tmp/.X11-unix
  #     - $HOME/.Xauthority:/home/gui/.Xauthority
  #   environment:
  #     - DISPLAY=${DISPLAY}
  #     # - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
  #     - ROS_DOMAIN_ID=42
  #   command: ros2 launch foxglove_bridge foxglove_bridge_launch.xml address:=localhost port:=8765

  opencv:
    build:
      context: .
      target: opencv
      args:
        USER: opencv
    <<: *common-env
    network_mode: host
    image: vision-tdk:opencv
    container_name: tdk-opencv
    environment:
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
      - ROS_DOMAIN_ID=24
    volumes:
        - $PWD/../packages:/home/opencv/vision-ws/src
    command: |
      bash -c "
      colcon build &&
      source install/setup.bash &&
      ros2 run opencv_ros orange
      "
  
  usbcam:
    build:
      context: .
      dockerfile: Dockerfile
      target: usbcam
    <<: *common-env
    image: vision-tdk:usbcam
    container_name: tdk-usbcam
    privileged: true
    devices:
      - /dev:/dev
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /dev:/dev
    environment:
      - ROS_DOMAIN_ID=24
    network_mode: host
    # command: bash
    command: |
      bash -c "
      source /opt/ros/humble/setup.bash
      colcon build
      source install/setup.bash
      ros2 run usb_cam usb_cam_node_exe
      "